// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riczjmholwwcfotopmkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpY3pqbWhvbHd3Y2ZvdG9wbWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNjY2ODIsImV4cCI6MjA1MTc0MjY4Mn0.t8Frbl_Co29kpNxr7CgCIdCdA3b43XQoGBMwZ7fTmVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);